// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYBuO655Mwz8ePhtB1kh5saqg9baNIFmw',
    appId: '1:12448289876:web:b8af538cd4d385bf2f89c1',
    messagingSenderId: '12448289876',
    projectId: 'koreksi-ujian-app',
    authDomain: 'koreksi-ujian-app.firebaseapp.com',
    storageBucket: 'koreksi-ujian-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALCBfTovb5Mev7Riv83qhmnwXI-vyy2d0',
    appId: '1:12448289876:android:613ed4eaa23b98802f89c1',
    messagingSenderId: '12448289876',
    projectId: 'koreksi-ujian-app',
    storageBucket: 'koreksi-ujian-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT07Z4X1naF-pLLa_aGCh-bB8B0h9C9Js',
    appId: '1:12448289876:ios:b10ab8780ce231312f89c1',
    messagingSenderId: '12448289876',
    projectId: 'koreksi-ujian-app',
    storageBucket: 'koreksi-ujian-app.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiKoreksiUjian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT07Z4X1naF-pLLa_aGCh-bB8B0h9C9Js',
    appId: '1:12448289876:ios:b10ab8780ce231312f89c1',
    messagingSenderId: '12448289876',
    projectId: 'koreksi-ujian-app',
    storageBucket: 'koreksi-ujian-app.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiKoreksiUjian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYBuO655Mwz8ePhtB1kh5saqg9baNIFmw',
    appId: '1:12448289876:web:5c336ee4baff92262f89c1',
    messagingSenderId: '12448289876',
    projectId: 'koreksi-ujian-app',
    authDomain: 'koreksi-ujian-app.firebaseapp.com',
    storageBucket: 'koreksi-ujian-app.firebasestorage.app',
  );
}
